---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: httpbin-repo
  namespace: flux-system
spec:
  url: https://github.com/danyapilovets/-httpbin-k8s-deployment
  interval: 30s
  ref:
    branch: main

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: httpbin-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/httpbin-cluster/environments
  prune: true
  sourceRef:
    kind: GitRepository
    name: httpbin-repo
  timeout: 2m
