replicaCount: 1

image:
  repository: kennethreitz/httpbin
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

securityContext:
  runAsUser: 10001
  runAsNonRoot: true
  fsGroup: 2000
