---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: httpbin
  namespace: prod
spec:
  interval: 5m
  chart:
    spec:
      chart: apps/httpbin/.charts/httpbin-0.1.0.tgz
      sourceRef:
        kind: GitRepository
        name: httpbin-repo
        namespace: flux-system
      interval: 1m
  targetNamespace: prod
