{{- $fullname := include "httpbin.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
  type: ClusterIP
